### PR TITLE
HSEARCH-2627 Use a proper JBoss Logger to log and to throw exceptions

### PR DESCRIPTION
**Pull request by mincong-h**
Hi Yoann, here's the PR for https://hibernate.atlassian.net/browse/HSEARCH-2627

### CODE REVIEW

**Comment by mincong-h** [comment]
I didn't have time to finish my work.. I'll send another PR later.

**Comment by yrodiere** [comment]
@mincong-h It's great that you're tackling this one! Just so you know, we don't use custom logger methods in tests. So the log.error(), warn() and info() should stay as is in tests. Thanks!

**Comment by mincong-h** [comment]
> @mincong-h It's great that you're tackling this one! Just so you know, we don't use custom logger methods in tests. So the log.error(), warn() and info() should stay as is in tests. Thanks!

Thanks Yoann, I didn't know that. I'll fix them later.

BTW, I added some more fixup this morning at my [topic branch](https://github.com/mincong-h/hibernate-search/commits/HSEARCH-2627-jboss-logger), but my Travis CI keep failing, for example the [last build](https://travis-ci.org/mincong-h/hibernate-search/builds/217953252#L9421) 😞 Do you know why?

**Comment by yrodiere** [comment]
> BTW, I added some more fixup this morning at my topic branch, but my Travis CI keep failing, for example the last build :disappointed: Do you know why?

The logger class implementation seems to be missing. You must add the following to your pom, so that a plugin will generate it for you:

```
            <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
            </plugin>
```

**Comment by mincong-h** [comment]
Thanks for your hint, you helped me to save a lot of time :100: :+1: :clap:
I sent a new PR, see #8.

**Pull request closed without merging**
