### PR TITLE
HSEARCH-2673 Throw exceptions or use addSuppressed instead of logging them in finally blocks 

### PR DESCRIPTION
**Pull request by yrodiere**
…f logging them in finally blocks

### CODE REVIEW

**Comment by mincong-h** [comment]
Hi @yrodiere , the checkstyle didn't pass—there's an unused import:

```
[ERROR] /home/travis/build/yrodiere/hibernate-search/jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java:10:15: Unused import - org.jboss.logging.Logger.Level.ERROR. [UnusedImports]
```

**Comment by yrodiere** [comment]
@mincong-h Right, sorry about that... I'll have a look tomorrow, I'm trying to hurry to fix another ticket before tomorrow.

**Comment by yrodiere** [comment]
@mincong-h It's all good now!

**Review by mincong-h — APPROVED** [review]
Looks good! 👍

**Comment by yrodiere** [comment]
Merged, thanks!

**Pull request merged**
