### PR TITLE
HSEARCH-2707 JSR-352: Review the default values for job parameters

### PR DESCRIPTION
**Pull request by mincong-h**
<https://hibernate.atlassian.net/browse/HSEARCH-2707>

Please merge #19 and #20 first. By the way, I didn't update the documentation yet. By sending this PR, I want to show that your fix works; and discuss the updated default values. Once validated, then I'll add the documentation part to it.

### CODE REVIEW

**Comment by yrodiere** [comment]
I don't think that `objectLoadingBatchSize` is equivalent to `checkpointInterval`.
From what I can see, we use a single value (`fetchSize`) for both `idFetchSize` and `objectLoadingBatchSize`; see `org.hibernate.search.jsr352.massindexing.impl.steps.lucene.PartitionMapper.buildScrollableResults(StatelessSession, Session, Class<?>, Set<Criterion>)` and `org.hibernate.search.jsr352.massindexing.impl.steps.lucene.EntityReader.buildScrollUsingCriteria(StatelessSession, PartitionBound, Object, JobContextData)`.
We may want to split them in the future, but for now I think it's fine.

In the end, `checkpointInterval` and `rowsPerPartition` do not have an equivalent in `MassIndexerImpl` as far as I can see.
So we must choose their default values ourselves.

It's probably a good idea to just give `rowsPerPartition` a default value that would be a multiple of `fetchSize`.
Basically `rowPerPartition` only has an effect on:

 * how large `checkpointInterval` can be (it must be smaller than `rowsPerPartition`)
 * how many threads one can keep busy (for a single entity type, that's at most `<number of entities>/<rowsPerPartition>`)

I wonder if, maybe, we shouldn't just compute `rowsPerPartition` automatically when it isn't set.
We could have a formula such as `sum(number of entities for each entity type)/(max(number of entity types, maxThreads) * <some hard-coded factor>)`. But that's probably something we should save for later.

For now, I think we should choose a value that's guaranteed to keep 5 threads (6 minus the "main" thread) busy for what we deem a "moderate" workload, while still allowing high values for `checkpointInterval` (if you have 10 million rows to process, you may not want 1 million checkpoints).
I suppose something like `500` would be quite safe:

 * it should keep all 5 threads busy during most of the execution above 10,000 entities (about 20 partitions, meaning that, worst case, we'll have idle threads for the last 4 partitions or only 20% of the time)
 * below 10,000 entities, indexing probably doesn't require much optimization anyway
 * it allows to choose a high `checkpointInterval` values, such as `100` (10,000/100 = 100 checkpoints, which seems reasonable)

And I'd use a default `checkpointInterval` of `100`, at least. Maybe even `200`. Remember each checkpoint requires a database access to write the current state of the work, so we probably don't want to use extra-low values such as `10`.

Of course, that's all wild guesses, so feel free to propose something else...

**Comment by mincong-h** [comment]
> I don't think that `objectLoadingBatchSize` is equivalent to `checkpointInterval`.
>
> From what I can see, we use a single value (`fetchSize`) for both `idFetchSize` and `objectLoadingBatchSize`; 

Thanks for reporting this. I created a ticket for it, see [HSEARCH-2786](https://hibernate.atlassian.net/browse/HSEARCH-2786). I'm not very sure how parameter `objectLoadingBatchSize` is used the existing implementation of `MassIndexer`, let's discuss together.

In the existing implementation `MassIndexerImpl`,

- In the 1st step, parameter `objectLoadingBatchSize` is set via `org.hibernate.search.MassIndexer`

- In the 2nd step, it is used when loading the entity IDs from stateless session, for measuring the capacity of each array list sent to the destination, see `IdentifierProducer.java`):

```java
// Excerpt from class org.hibernate.search.batchindexing.impl.IdentifierProducer

private void loadAllIdentifiers(final StatelessSession session) throws InterruptedException {
	...
	ArrayList<Serializable> destinationList = new ArrayList<Serializable>( batchSize );
	long counter = 0;
	try {
		while ( results.next() ) {
			Serializable id = (Serializable) results.get( 0 );
			destinationList.add( id );
			if ( destinationList.size() == batchSize ) {
```

- In the 3rd step, a batch of IDs is taken from the queue repeatedly to produce documents until there's no more batch to take. In this step, the batch size is `objectLoadingBatchSize`, defined in the previous step. See `IdentifierConsumerDocumentProducer`.

Now, let's take a look for JSR-352 implementation. When loading the loading the entity IDs, only the parameter `fetchSize` is used, so you're right about this point: `objectLoadingBatchSize` is replaced by `fetchSize` for similar usage, and `checkpointInterval` is never used. Then, let's take a look in class `LuceneDocWriter`. Here, the entities to write are by batch as in the 3rd step of the previous approach. `LuceneDocWriter#writeItems(List)` accepts a list of objects to write into Lucene documents, where the size of the list is defined as `checkpointInterval`. **As we're in a chunk-oriented processing, the size of the chunk and the checkpoint interval are the same value.** From §7.9 Batch Checkpoints, spec 1.0 (page 18):

> Checkpoints work naturally with chunk-oriented processing. The end of processing for each chunk is a natural point for taking a checkpoint.

The size of a batch `objectLoadingBatchSize` has became the size of the chunk as `checkpointInterval`. So I think they are still a nice match, but we should rename `checkpointInterval` to something more general though...

**Comment by mincong-h** [comment]
- [x] The default value of `rowsPerPartition=1000` is now a multiple of `fetchSize=100`
- [x] The default value of `checkpointInterval` is now set to `200`.
- [x] The default value of `maxThreads` is now set to `10`, because theoretically we can ask as many threads as we can, so I'd rather give a higher value. <sup>[1]</sup>
- [x] The documentation has been updated.

<sup>[1]</sup> I'm even wondering if we should avoid defining this value? Because when it is not defined, the default is the number of partitions (§8.2.6.1, spec 1.0, page 34), which can be super high. Should we do that? (It assumes that user always wants to use as many threads as possible)

**Comment by mincong-h** [comment]
> I wonder if, maybe, we shouldn't just compute `rowsPerPartition` automatically when it isn't set.
We could have a formula such as `sum(number of entities for each entity type)/(max(number of entity types, maxThreads) * <some hard-coded factor>)`. But that's probably something we should save for later.

Not sure the motivation of this change & the meaning of this formula, could we discuss it later?

**Comment by yrodiere** [comment]
# Chunk and fetch size

## What is the equivalent of `objectLoadingBatchSize` in the JSR-352 integration?

> The size of a batch objectLoadingBatchSize has became the size of the chunk as checkpointInterval. So I think they are still a nice match, but we should rename checkpointInterval to something more general though...

You're right: `objectLoadingBatchSize` is equivalent to `checkpointInterval` in that it defines how many entities will be in a chunk (the chunk size). I didn't see that at first, so I will elaborate a bit...

What is different is that `objectLoadingBatchSize` also directly defines the *fetch* size:

* `org.hibernate.search.batchindexing.impl.IdentifierConsumerDocumentProducer.loadAllFromQueue(SessionImplementor)` is where the IDs (lists of at most `objectLoadingBatchSize` identifiers`) are consumed
* it calls `org.hibernate.search.batchindexing.impl.IdentifierConsumerDocumentProducer.loadList(List<Serializable>, SessionImplementor, InstanceInitializer)`, which calls this: `.setFetchSize( listIds.size() )`.

So I'd say that on our side, we have two different variables instead of one for  `objectLoadingBatchSize`: `checkpointInterval` to define the documents batch size when writing to the index (= "chunk size"), and `fetchSize` to define the entity batch size when reading from the database (let's call that "fetch size").

## Is it a good idea to have two distinct variables?

I think there are good reasons to keep the fetch size higher than the chunk size; for instance if there is a high latency between the application server and the database, you may want to make the batches as big as possible, reducing the impact of latency (less fetches means less time spent waiting). Which doesn't mean you want to increase the chunk size: batch jobs may very well be persisted to a different database.

I guess there _could_ be good reasons to keep the fetch size _lower_ than the chunk size, for example if you want a very high chunk size (to keep the checkpoints, and thus the persistence of job status to a minimum) but don't want to fill the JVM heap with thousands of managed entities.

## What does it mean for the default values

I suppose database latency is always too high, but I think most setups try to keep it as low as possible (otherwise the whole application will be very slow). So I don't think we should try to make the fetch size particularly high compared to the chunk size.

As to whether those default values should be `10` (as in `MassIndexerImpl`) or higher... I honestly don't know. `10` seems aggressively low, but it's probably been set after careful benchmarks. On the other hand, the processing model in our JSR-352 integration is a bit different, so what was best for `MassIndexerImpl` may not be best in our case.

I'd say let's keep what you did, and we'll fine-tune the default values later, when we do some benchmarking.

# Other topics

>  The default value of rowsPerPartition=1000 is now a multiple of fetchSize=100
>  The default value of checkpointInterval is now set to 200.
>  The default value of maxThreads is now set to 10, because theoretically we can ask as many threads as we can, so I'd rather give a higher value. [1]

Looks good to me.

> [1] I'm even wondering if we should avoid defining this value? Because when it is not defined, the default is the number of partitions (§8.2.6.1, spec 1.0, page 34), which can be super high. Should we do that? (It assumes that user always wants to use as many threads as possible)

Let's not make it unlimited by default: Sanne tends to not like when we spawn many threads :) We can create a ticket and discuss it with him if you want, though.

>  The documentation has been updated.

Looks good!

Merged, thanks!

**Comment by mincong-h** [comment]
> > [1] I'm even wondering if we should avoid defining this value? Because when it is not defined, the default is the number of partitions (§8.2.6.1, spec 1.0, page 34), which can be super high. Should we do that? (It assumes that user always wants to use as many threads as possible)
> 
> Let's not make it unlimited by default: Sanne tends to not like when we spawn many threads :) We can create a ticket and discuss it with him if you want, though.
> 

Ticket created <https://hibernate.atlassian.net/browse/HSEARCH-2803>

**Pull request merged**
